/**
 * TokenizationStrategy defines the interface for tokenization strategies.
 */
class TokenizationStrategy {
    /**
     * Applies the strategy to the tokenizer.
     * @param {Tokenizer} tokenizer - The tokenizer instance.
     * @returns {Object} The token generated by this strategy.
     */
    apply(tokenizer) {
        throw new Error("Method 'apply()' must be implemented.");
    }
}

export default TokenizationStrategy;
