/**
 * TokenizationStrategy defines the interface for tokenization strategies.
 *
 * This class provides the blueprint for all tokenization strategies that are used
 * within the tokenizer. Each subclass is expected to implement the `apply` method,
 * which defines how a specific strategy tokenizes input.
 *
 * @author Taahir Suleman
 */
class TokenizationStrategy {
    /**
     * Applies the strategy to the tokenizer.
     *
     * This method is expected to be overridden by any subclass that implements a
     * specific tokenization strategy. The method takes the current instance of
     * the tokenizer and generates a token based on that strategy.
     *
     * @param {Tokenizer} tokenizer - The tokenizer instance.
     * @returns {Object} The token generated by this strategy.
     * @throws {Error} Throws an error if the method is not implemented by the subclass.
     */
    apply(tokenizer) {
        throw new Error("Method 'apply()' must be implemented.");
    }
}

export default TokenizationStrategy;
